on: [ push, pull_request ]

name: Go Integration Test

jobs:
  it-local:
    name: local s3
    runs-on: ubuntu-latest
    env:
      LOCAL_S3: true
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
      - name: Start local S3
        run: docker-compose up -d
      - name: Run integration tests
        run: go test -v ./...
      - name: Stop local S3
        if: always()
        run: docker-compose down
